### ISSUE TITLE
Non-full blocks

### ISSUE THREAD

**Issue by Heath123** [fenomas/fast-voxel-raycast#2]
Non-full blocks seem to work in noa, but I can't see how to make them work with this. Would it be possible to add support for non-full blocks or documentation for it if it's already possible? Thank you

**Comment by fenomas** [comment]
Hi, unfortunately neither this library or the engine support non-full blocks at the moment. The engine has "object blocks", which can visually look non-full, but it treats them as either fully solid or fully empty for the purposes of raycasting and physics and so forth.

Adding support for this would be cool, and I'd like to do it at some point but haven't yet looked at it carefully...
